=== adrialhama/LenguajesDeMarcas2122/Unidad_04_DTD_XSD/DTD/Examen/peliculaMiedo.dtd
<!ELEMENT pelisDeMiedo (#PCDATA | year)*>
<!ENTITY % peli "
<!ATTLIST pelicula
    nombre CDATA #REQUIRED
    personaje ID #REQUIRED
    aparicion IDREF #IMPLIED
    conoce IDREFS #IMPLIED
>
">
<!ELEMENT year (pelicula | serie? | puntuacion)*>
<!ELEMENT pelicula EMPTY>
%peli;
<!ELEMENT serie (#PCDATA)>
<!ELEMENT puntuacion (positiva+ | negativa?)>
<!ELEMENT positiva EMPTY>
<!ELEMENT negativa EMPTY>
<!ATTLIST positiva ranking CDATA #FIXED "Es buena">
<!ATTLIST year epoca (1970 | 1980 | 1990 | 2000 | 2010 | 2021) #IMPLIED>

=== adrialhama/LenguajesDeMarcas2122/Unidad_04_DTD_XSD/DTD/Examen/peliculaMiedo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelisDeMiedo SYSTEM "peliculaMiedo.dtd">

<pelisDeMiedo>
    Las mejores películas de terror
    <year epoca="1980">
        <pelicula nombre="El exorcista" personaje="Cura"/>
        <puntuacion>
            <positiva ranking="Es buena"/>
        </puntuacion>    
    </year>
    <year epoca="1990">
        <pelicula nombre="Pesadilla en Elm Street" personaje="FreddyKruegger"/>   
        <pelicula nombre="El muñeco diabólico" personaje="Chucky" conoce="FamiliaDefeo FreddyKruegger"/>  
        <puntuacion>
            <positiva ranking="Es buena"/>
        </puntuacion>
        <puntuacion>
            <negativa/>
        </puntuacion> 
    </year>
    <year epoca="2000">
        <pelicula nombre="Amitville" personaje="FamiliaDefeo" aparicion="EdYLorein"/>    
        <puntuacion>
            <positiva ranking="Es buena"/>
        </puntuacion>
    </year>
    <year epoca="2021">
        <pelicula nombre="Expediente Warren" personaje="EdYLorein"/>
        <puntuacion>
            <positiva ranking="Es buena"/>
        </puntuacion>
        <serie>El juego del Calamar</serie>    
    </year>
</pelisDeMiedo>
